### ISSUE TITLE
feature request: write out notebooks with 'not implemented yet' message

### ISSUE THREAD

**Issue by fotisj** [d2l-ai/d2l-book#18]
At the moment, it seems the build system creates empty notebooks for those branches where there is no tab yet (for example some of the pytorch parts in some notebooks in the d2l book). It would be useful to create the notebooks (with all texts and images) and include there, where the code should be, a message which says 'not implemented yet'.

**Comment by AnirudhDagar** [comment]
This was fixed by https://github.com/d2l-ai/d2l-book/pull/51. There are no more empty notebooks created by the build system. We decided to just skip creation of those notebooks until the chapter was implemented.
