### ISSUE TITLE
Minor style issues caused by yapf

### ISSUE THREAD

**Issue by astonzhang** [d2l-ai/d2l-book#26]
Thanks to https://github.com/d2l-ai/d2l-book/commit/06ce6657f279af162da845dd3d771ae6a61f1700, now D2L replaces fluent alias (e.g., d2l.reshape(a, (1,2)) -> a.reshape((1,2))) correctly!

Due to the use of `yapf` in the code prettification step, the following are new minor style issues:

* `d2l.plt.scatter(d2l.numpy(features[:, 1]), d2l.numpy(labels), 1);` will become `d2l.plt.scatter(features[:, (1)].asnumpy(), labels.asnumpy(), 1)`, where the trailing semicolon (useful for showing figures only in notebooks) is trimmed and `1` is surrounded with unnecessary parentheses.

<img width="689" alt="Screen Shot 2021-01-19 at 10 46 58 PM" src="https://user-images.githubusercontent.com/22279212/105137515-45622e80-5aa8-11eb-82c4-c548af8fc48c.png">

* `yapf` may unnecessarily produce two empty lines instead of one empty line (space inefficient for physical books):

<img width="720" alt="Screen Shot 2021-01-19 at 10 47 44 PM" src="https://user-images.githubusercontent.com/22279212/105137576-6034a300-5aa8-11eb-976e-ddacdad1fe4e.png">

* `yapf` may unnecessarily produce empty lines within our import blocks (space inefficient for physical books):

<img width="494" alt="Screen Shot 2021-01-19 at 10 48 35 PM" src="https://user-images.githubusercontent.com/22279212/105137632-7b9fae00-5aa8-11eb-9a24-1413887be378.png">

**Comment by mli** [comment]
2) is by https://github.com/d2l-ai/d2l-book/commit/486cb8d2473330d200cee86efceed8d66f26804b

**Comment by mli** [comment]
3. ix fixed by https://github.com/d2l-ai/d2l-book/commit/caca84a75ae014c9ef84d7ce91dde38c92860507

**Comment by mli** [comment]
1. is fixed by https://github.com/d2l-ai/d2l-book/commit/6e7a7afd57f1d6c376e4350f4784627b6de29e72
2.
