### ISSUE TITLE
Unexpected error while saving file: xxx display_priority.j2

### ISSUE THREAD

**Issue by astonzhang** [d2l-ai/d2l-book#59]
Note that `d2lbook` has two dependencies: `nbconvert` and `mu-notedown`. For nbconvert>=6.2.0 (nbconvert 6.0.0 and 6.1.0 have other issues when running `jupyter notebook`), when using Jupyter Notebook to edit a markdown file (enabled by mu-notedown), saving a file throws the following error message:

![Screen Shot 2022-08-02 at 9 41 04 PM](https://user-images.githubusercontent.com/22279212/182526281-1c4c924e-9ed8-4cec-b77f-c669b8cec946.png)

In my locale, editing 

`~/miniconda3/envs/np3/lib/python3.9/site-packages/notedown/templates/markdown.tpl`
or
`~/miniconda3/envs/np3/lib/python3.8/site-packages/mu_notedown-2.0.3-py3.8.egg/notedown/templates/markdown.tpl`

as  https://github.com/aaren/notedown/pull/96/files resolves the issue.

Thus, the following changes are proposed:

* Edit https://github.com/mli/notedown/blob/master/setup.py#L19 as `'nbconvert>=6.2.0',`
* Edit https://github.com/mli/notedown/blob/master/notedown/templates/markdown.tpl#L1 as `{% extends 'base/display_priority.j2' %}`
* Upload an upgraded version of `mu-notedown` after bumping a version at https://github.com/mli/notedown/blob/master/setup.py#L10
* Remove https://github.com/d2l-ai/d2l-book/blob/master/setup.py#L11-L12 since both are required in `mu-notedown`

Related discussions:

https://github.com/aaren/notedown/pull/96/files
https://github.com/aaren/notedown/issues/95
https://github.com/jupyter/nbconvert/issues/1369

**Comment by AnirudhDagar** [comment]
Fixed in https://github.com/d2l-ai/notedown/pull/3
